import type { SQLITE_TYPES } from '../utils/sqlite.types';
import { type ColumnMetadata } from './query-builder';
import { readFileSync, writeFileSync } from 'fs';
import { existsSync, mkdirSync } from 'fs';
import { dirname, join } from 'path';

export function mapType(sqlType: SQLITE_TYPES): string {
  if (sqlType.startsWith('VARCHAR')) {
    return 'string';
  }
  switch (sqlType) {
    case 'INTEGER':
      return 'number';
    case 'TEXT':
    case 'DATE':
    case 'DATETIME':
    case 'TIMESTAMP':
    case 'UUID':
      return 'string';
    case 'BOOLEAN':
      return 'boolean';
    case 'FLOAT':
      return 'number';
    default:
      return 'any';
  }
}

function generateSingleFileTypes(
  tableName: string,
  columns: Record<string, ColumnMetadata>,
  filePath: string
) {
  const selectFields = Object.entries(columns)
    .map(([name, meta]) => `  ${name}: ${meta.tsType}${meta.nullable ? ' | null' : ''};`)
    .join('\n');

  const insertFields = Object.entries(columns)
    .filter(([_, meta]) => !meta.isPrimary)
    .map(([name, meta]) => `  ${name}${meta.nullable || meta.hasDefault ? '?' : ''}: ${meta.tsType}${meta.nullable ? ' | null' : ''};`)
    .join('\n');

  const selectInterface = `export interface ${tableName}Select {\n${selectFields}\n}`;
  const insertInterface = `export interface ${tableName}Insert {\n${insertFields}\n}`;
  const updateType = `export type ${tableName}Update = Partial<Omit<${tableName}Insert, 'id'>> & { id: number };`;

  const newTableBlock = `// --- Table: ${tableName} Start ---
${selectInterface}

${insertInterface}

${updateType}
// --- Table: ${tableName} End ---`;

  let existingTables: Record<string, string> = {};

  if (existsSync(filePath)) {
    try {
      const content = readFileSync(filePath, 'utf-8');
      const tableRegex = /\/\/\s*---\s*Table:\s*(\w+)\s*Start\s*---([\s\S]*?)\/\/\s*---\s*Table:\s*\1\s*End\s*---/g;
      let match;
      while ((match = tableRegex.exec(content)) !== null) {
        const existingTableName = match[1];
        existingTables[existingTableName] = match[0];
      }
    } catch (e) {
      console.warn(`Could not read existing types file ${filePath}:`, e);
    }
  }

  existingTables[tableName] = newTableBlock;

  const tableBlocks = Object.values(existingTables).join('\n\n');

  const tableMapEntries = Object.keys(existingTables)
    .map((name) => `  ${name}: {\n    select: ${name}Select;\n    insert: ${name}Insert;\n    update: ${name}Update;\n  };`)
    .join('\n');

  const newContent = `// Auto-generated by bun-sqlight. Do not edit.

${tableBlocks}

export interface TableMap {
${tableMapEntries}
}

export type TableTypes = TableMap;
`;

  try {
    const dir = dirname(filePath);
    if (!existsSync(dir)) {
      mkdirSync(dir, { recursive: true });
    }
    writeFileSync(filePath, newContent);
  } catch (e) {
    console.error(`Failed to write types to ${filePath}:`, e);
  }
}

export function generateTableTypes(
  tableName: string,
  columns: Record<string, ColumnMetadata>,
  options?: { typesOutputFile?: string }
) {
  console.log({ tableName, columns });
  const selectFields = Object.entries(columns)
    .map(([name, meta]) => `${name}: ${meta.tsType}${meta.nullable ? ' | null' : ''}`)
    .join('\n  ');

  const insertFields = Object.entries(columns)
    .filter(([_, meta]) => !meta.isPrimary) // Ignora PK auto gerada
    .map(([name, meta]) => `${name}${meta.nullable || meta.hasDefault ? '?' : ''}: ${meta.tsType}${meta.nullable ? ' | null' : ''}`)
    .join('\n  ');

  const updateType = `Partial<Omit<${tableName}Insert, 'id'>> & { id: number }`;

  const typeContent = `
// Auto-generated types for ${tableName}
export interface ${tableName}Select {
  ${selectFields}
}

export interface ${tableName}Insert {
  ${insertFields}
}

export type ${tableName}Update = ${updateType};
  `;
  const generatedDir = join(import.meta.dir, '..', 'generated');
  const typeFilePath = join(generatedDir, `${tableName}.types.ts`);
  if (!existsSync(generatedDir)) {
    mkdirSync(generatedDir, { recursive: true });
  }
  writeFileSync(typeFilePath, typeContent);

  const indexPath = join(generatedDir, 'index.ts');
  const replaceLabel = '//$___';
  if (!existsSync(indexPath)) {
    writeFileSync(
      indexPath,
      `
      // Auto-generated index for table types
      export default class TableTypes {\n\n      //${replaceLabel}\n    }
      `
    );
  }
  let indexContent = readFileSync(indexPath, 'utf-8');
  const importStatement = `import { type ${tableName}Select, type ${tableName}Insert, type ${tableName}Update } from './${tableName}.types';`;
  const tableTypeEntry = `  \nstatic ${tableName}: {\n    select: ${tableName}Select,\n    insert: ${tableName}Insert,\n    update: ${tableName}Update,\n  }`;

  if (!indexContent.includes(importStatement)) {
    indexContent = `${importStatement}\n${indexContent}`;
  }

  if (!indexContent.includes(tableTypeEntry)) {
    indexContent = indexContent.replace(replaceLabel, `${tableTypeEntry}\n${replaceLabel}`);
  }

  writeFileSync(indexPath, indexContent);

  const typesOutputFile = options?.typesOutputFile || process.env.SQLIGHT_GENERATE_PATH;
  if (typesOutputFile) {
    generateSingleFileTypes(tableName, columns, typesOutputFile);
  }
}
